#!/bin/sh
set -euf
# build all the parts together

#- mtd0 -> uboot (probably need to rebuild)
#- mtd1 -> wr703 specific data
#- mtd2 -> the openwrt image
#- mtd3 -> virtual partition (do not use)
#- mtd5_empty -> filler for the new space we have
#- mtd4 -> art file (needs to be at the end)
#
#cat images/wr703_exc0/mtd0 images/wr703_exc0/mtd1 images/wr703_exc0/mtd2 wr703/mtd5_empty.bin images/wr703_exc0/mtd4 > big_exc0.bin
default_free_space=4m 
default_model=wr703n
#TODO calculate free disk space by substracting the image size from the
#     complete size
usage(){
  cat <<EOF
usage: [env] $0 image-name

env:
  model=<wr703n,mr3020>     - the model of the image, required for uboot loader
                           choice
  free_space=<4m,12m>    - the size of the free disk space
  
Info:
  image-name is a folder in images/ which contains: 
      mtd1 (kernel)
      mtd2 (openwrt-image)
      mtd4 (art partition)
    
EOF
}
if test -n "${free_space:-}";then
  echo "using given value of free space: $free_space"
else
  free_space=$default_free_space
  echo "using default free disk size of $free_space"
fi

if test -n "${model:-}";then
  echo "using given value of model: $model"
  model_file=${model}.bin
  ! test -e images/uboot/${model_file} && \
    echo "no bootloader available for model ${model}.Bailing out" && \
    exit 1
else
  model_file=${default_model}.bin
  echo "using default model of $default_model"
fi
echo
test "$#" -eq 0 && usage && exit 1

! test -e "images/$1" && echo "profile 'images/$1' does not exist"  && exit 1
outfile="$1_big.bin"
cd "images/$1"

for i in mtd1 mtd2 mtd4;do
  ! test -e $i && echo "$i does not exist in profile"
done

rm -f mtd5_empty
truncate --size $free_space mtd5_empty

echo "creating new image with additional '$free_space' of space to images/$outfile"

cat "../uboot/${model_file}" mtd1 mtd2 mtd5_empty mtd4 > "../$outfile"
cd ../..
ls -l "images/$outfile" || echo "something went wrong :(" 
echo "finished"
